CREATE TABLE CLIENTES (
    cli_id NUMBER(6) NOT NULL,
    cli_pnome VARCHAR2(30),
    cli_mnome VARCHAR2(30),
    cli_unome VARCHAR2(30)
);

CREATE TABLE PRODUTOS (
    pro_id NUMBER(6) NOT NULL,
    pro_nome VARCHAR2(30),
    pro_valor NUMBER(10, 2)
);

CREATE TABLE PEDIDOS (
    ped_id NUMBER(6) NOT NULL,
    ped_data DATE,
    ped_valor_final NUMBER(10, 2),
    ped_cli_id NUMBER(6) NOT NULL
);

CREATE TABLE ITENS_PEDIDO (
    ite_id NUMBER(6) NOT NULL,
    ite_ped_id NUMBER(6) NOT NULL,
    ite_pro_id NUMBER(6) NOT NULL
);

-- Pk's
ALTER TABLE CLIENTES ADD CONSTRAINT cli_pk PRIMARY KEY (cli_id);
ALTER TABLE PRODUTOS ADD CONSTRAINT pro_pk PRIMARY KEY (pro_id);
ALTER TABLE PEDIDOS ADD CONSTRAINT ped_pk PRIMARY KEY (ped_id);
ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT ite_pk PRIMARY KEY (ite_id);


-- FK's 
ALTER TABLE PEDIDOS 
    ADD CONSTRAINT ped_cli_fk FOREIGN KEY (ped_cli_id) 
    REFERENCES CLIENTES (cli_id);

ALTER TABLE ITENS_PEDIDO 
    ADD CONSTRAINT ite_ped_fk FOREIGN KEY (ite_ped_id) 
    REFERENCES PEDIDOS (ped_id);

ALTER TABLE ITENS_PEDIDO 
    ADD CONSTRAINT ite_pro_fk FOREIGN KEY (ite_pro_id) 
    REFERENCES PRODUTOS (pro_id);

-- SEQUENCES
CREATE SEQUENCE cli_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE pro_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ped_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ite_seq START WITH 1 INCREMENT BY 1;

-- TRIGGERS

CREATE OR REPLACE TRIGGER cli_trg 
BEFORE INSERT ON CLIENTES 
FOR EACH ROW 
BEGIN 
    IF :NEW.cli_id IS NULL THEN 
        SELECT cli_seq.NEXTVAL INTO :NEW.cli_id FROM dual; 
    END IF; 
END;
/

CREATE OR REPLACE TRIGGER pro_trg 
BEFORE INSERT ON PRODUTOS 
FOR EACH ROW 
BEGIN 
    IF :NEW.pro_id IS NULL THEN 
        SELECT pro_seq.NEXTVAL INTO :NEW.pro_id FROM dual; 
    END IF; 
END;
/

CREATE OR REPLACE TRIGGER ped_trg 
BEFORE INSERT ON PEDIDOS 
FOR EACH ROW 
BEGIN 
    IF :NEW.ped_id IS NULL THEN 
        SELECT ped_seq.NEXTVAL INTO :NEW.ped_id FROM dual; 
    END IF; 
END;
/

CREATE OR REPLACE TRIGGER ite_trg 
BEFORE INSERT ON ITENS_PEDIDO 
FOR EACH ROW 
BEGIN 
    IF :NEW.ite_id IS NULL THEN 
        SELECT ite_seq.NEXTVAL INTO :NEW.ite_id FROM dual; 
    END IF; 
END;
/
